[phases.setup]
    nixPkgs = ['php81', 'php81Packages.composer', 'nodejs']

[phases.install]
    cmds = ['composer install --frozen-lockfile --no-dev']

[phases.build]
    cmds = ['npm install && npm run build', 'php artisan config:cache']
